"""Write the in-app manual out as one document — ``doc/user_guide.md`` and
its PDF — so the copy in the repository is generated, never hand-kept.

    python -m pysurvanalysis.help.export            # doc/user_guide.md + .pdf
    python -m pysurvanalysis.help.export --no-pdf

The test suite checks the Markdown copy matches the pages, so a page edited
without re-exporting is caught rather than left to drift (the old hand-written
guide described a command line that no longer existed).
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from . import pages
from .manifest import CHAPTERS

REPO_DOC = Path(__file__).resolve().parents[2] / "doc"
_HELP_LINK = re.compile(r"\]\(help:([A-Za-z0-9_-]+)\)")

_HEADER = """# pySurvAnalysis — User Guide

This guide is the in-app manual (Help in the Analysis Hub, F1 or any **?**
button), exported as one document. Generated by
`python -m pysurvanalysis.help.export` — edit the pages in
`pysurvanalysis/help/topics/`, not this file.
"""


def manual_markdown() -> str:
    """Every page in manual order behind a linked table of contents; links
    between pages become links within the document."""
    out = [_HEADER, "## Contents\n"]
    for chapter, topics in CHAPTERS:
        out.append(f"**{chapter}**\n")
        out.extend(f"- [{title}](#{topic})" for topic, title in topics)
        out.append("")
    for chapter, topics in CHAPTERS:
        out.append(f"\n---\n\n# {chapter}\n")
        for topic, _title in topics:
            text = pages.page_text(topic).strip()
            ## One level down, so each chapter heading stays the top level.
            text = re.sub(r"^(#{1,5}) ", lambda m: "#" + m.group(1) + " ", text,
                          flags=re.M)
            text = _HELP_LINK.sub(lambda m: f"](#{m.group(1)})", text)
            out.append(f'<a id="{topic}"></a>\n\n{text}\n')
    return "\n".join(out).rstrip() + "\n"


def write_markdown(path: Path | None = None) -> Path:
    path = Path(path or REPO_DOC / "user_guide.md")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(manual_markdown(), encoding="utf-8", newline="\n")
    return path


def write_pdf(path: Path | None = None) -> Path:
    """The same document typeset by Qt — the renderer the in-app manual uses,
    so the PDF reads like the window."""
    from PyQt6.QtCore import QMarginsF
    from PyQt6.QtGui import QGuiApplication, QPageLayout, QPageSize, QPdfWriter, QTextDocument

    app = QGuiApplication.instance() or QGuiApplication([])  # noqa: F841 - fonts need one
    path = Path(path or REPO_DOC / "user_guide.pdf")
    path.parent.mkdir(parents=True, exist_ok=True)
    writer = QPdfWriter(str(path))
    writer.setPageLayout(QPageLayout(QPageSize(QPageSize.PageSizeId.A4),
                                     QPageLayout.Orientation.Portrait,
                                     QMarginsF(18, 18, 18, 18),
                                     QPageLayout.Unit.Millimeter))
    writer.setTitle("pySurvAnalysis — User Guide")
    document = QTextDocument()
    ## Anchors are HTML, which the Markdown importer would print literally.
    document.setMarkdown(re.sub(r'<a id="[^"]+"></a>\n', "", manual_markdown()))
    document.print(writer)
    return path


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--no-pdf", action="store_true", help="Markdown only.")
    args = parser.parse_args(argv)
    print(f"Wrote {write_markdown()}")
    if not args.no_pdf:
        print(f"Wrote {write_pdf()}")


if __name__ == "__main__":
    main()
